services:
  java_app:
    container_name: java-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file: .env.app
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./bin/postgres_data:/var/lib/postgresql/data
      - ./bin/scripts_db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file: .env.db